---
- hosts: all
  become: 'yes'
  vars:
    flags:
        kyoto: acpi_backlight=video
        tokyo: pci=noats
        omura: pci=noats
  pre_tasks:
    - name: get hostname
      command: hostname
      register: hostname
    - name: check if machine needs boot flags
      meta: end_play
      when: hostname.stdout not in flags
  tasks:
    - name: remove old grub boot flags
      lineinfile:
        path: /etc/default/grub
        search_string: GRUB_CMDLINE_LINUX=
        state: absent
    - name: add new grub boot flag
      lineinfile:
        path: /etc/default/grub
        insertafter: GRUB_CMDLINE_LINUX_DEFAULT
        line: GRUB_CMDLINE_LINUX="{{ flags[hostname.stdout] }}"
        state: present
    - name: regenerate grub.cfg
      command: grub-mkconfig -o /boot/grub/grub.cfg

