---
- hosts: all
  become: yes
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{ playbook_dir }}/vars"
    - name: add nobody to sudoers 
      lineinfile:
        path: /etc/sudoers
        insertafter: User privilege specification
        line: nobody	ALL=(ALL:ALL) NOPASSWD: ALL
  tasks:
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        status: latest
      become_method: su
      become_user: nobody
      become_flags: -s /bin/sh
    - name: update package list
      kewlfft.aur.aur:
        update_cache: yes
        aur_only: yes
      become_method: su
      become_user: nobody
      become_flags: -s /bin/sh
    - name: install aur packages
      kewlfft.aur.aur:
        name: "{{ item }}"
        status: latest
      become_method: su
      become_user: nobody
      become_flags: -s /bin/sh
      loop: "{{ packages_aur }}"
  post_tasks:
    - name: remove nobody from sudoers
      lineinfile:
        path: /etc/sudoers
        search_string: 'nobody	ALL=(ALL:ALL) NOPASSWD: ALL'
        state: absent
