---
- hosts: all
  become: yes
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{ playbook_dir }}/vars"
    - name: check for existing hooks
      command: grep -q setvtrgb /etc/mkinitcpio.conf
      register: hashook
  tasks:
    - name: set colorscheme
      ansible.builtin.file:
        src: usr/share/kbd/consolecolors/base16-"{{ colorscheme }}".vga
        dest: /etc/vtrgb
        state: link
        force: yes
    - name: add hooks
      when: not hashook
      ansible.builtin.replace:
        path: /etc/mkinitcpio.conf
        regexp: '^HOOKS=\('
        replace: 'HOOKS=(setvtrgb consolefont'
  post_tasks:
    - name: run mkinitcpio
      command: mkinitcpio -plinux
