---
- hosts: all
  become: yes
  vars:
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{ playbook_dir }}/vars"
    - name: get hostname
      command: "cat /etc/hostname"
      register: hostname
    - name: check if machine needs boot flags
      meta: end_play
      when: hostname.stdout not in flags
  tasks:
    - name: add grub boot flags
      replace:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX=\"+'
        replace: GRUB_CMDLINE_LINUX="{{ flags[hostname.stdout] }}"
      ignore_errors: yes
  post_tasks:
    - name: regenerate grub.cfg
      command: grub-mkconfig -o /boot/grub/grub.cfg

