---
- hosts: all
  become: yes
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{ playbook_dir }}/vars"
    - name: add {{ user }} to sudoers 
      lineinfile:
        path: /etc/sudoers
        insertafter: "@includedir /etc/sudoers.d"
        line: "{{ user }}	ALL=(ALL:ALL) NOPASSWD: ALL"
  tasks:
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present
      become_method: su
      become_user: "{{ user }}"
    - name: update package list and upgrade
      kewlfft.aur.aur:
        update_cache: yes
        upgrade: yes
        aur_only: yes
      become_method: su
      become_user: "{{ user }}"
      become_flags: -s /bin/sh
    - name: install aur packages
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: latest
      become_method: su
      become_user: "{{ user }}"
      become_flags: -s /bin/sh
      loop: "{{ packages_aur }}"
  post_tasks:
    - name: remove {{ user }} from sudoers
      lineinfile:
        path: /etc/sudoers
        search_string: "{{ user}}	ALL=(ALL:ALL) NOPASSWD: ALL"
        state: absent
