---
- hosts: all
  become: yes
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{ playbook_dir }}/vars"
  tasks:
    - name: configure greetd for desktop (sway)
      ansible.builtin.replace:
        path: /etc/greetd/config.toml
        regexp: 'command = .+'
        replace: 'command = {{ greetd_command_desktop }}'
      when: desktop is defined
    - name: configure greetd for laptop (cage)
      ansible.builtin.replace:
        path: /etc/greetd/config.toml
        regexp: 'command = .+'
        replace: 'command = {{ greetd_command_laptop }}'
      when: desktop is not defined
    - name: copy sway config for greetd
      copy:
        src: "{{ playbook_dir }}/assets/sway_config"
        dest: /etc/greetd/sway-config
        when: desktop is defined
    - name: copy gtkgreet css
      copy:
        src: "{{ playbook_dir }}/assets/gtkgreet_style.css"
        dest: /etc/greetd/gtkgreet_style.css
      when: desktop is defined
    - name: copy gtkgreet background jpg
      copy:
        src: "{{ playbook_dir }}/assets/login.jpg"
        dest: /etc/greetd/login.jpg
