---
- hosts: all
  become: yes
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{ playbook_dir }}/vars"
  tasks:
    - name: configure greetd
      ansible.builtin.replace:
        path: /etc/greetd/config.toml
        regexp: 'command = .+'
        replace: 'command = {{ greetd_command }}'
    - name: copy gtkgreet css
      copy:
        src: "{{ playbook_dir }}/assets/gtkgreet_style.css"
        dest: /etc/greetd/gtkgreet_style.css
    - name: copy gtkgreet background jpg
      copy:
        src: "{{ playbook_dir }}/assets/login.jpg"
        dest: /etc/greetd/login.jpg
